//
//  MyHero.m
//  Quest
//
//  Created by Leo Linsky on 5/18/12.
//  Copyright (c) 2012 __MyCompanyName__. All rights reserved.
//

#import "MyHero.h"

@implementation MyHero

@synthesize beatBoss1, freeSteps,wentEllemakPostSaveKing,wentEllemakPostBeatIonak;
@synthesize gotItem1,gotItem2,gotItem3,gotItem4,gotItem5,gotItem6,gotItem7,gotItem8,gotItem9,gotItem10,gotItem11,gotItem12,gotItem13,gotItem14,gotItem15,gotItem16,gotItem17,gotItem18,gotItem19,gotItem20,gotLorica,gotItem21,gotItem22,gotItem23,gotItem24,gotItem25,gotItem26,gotItem27,gotItem28,gotItem29,gotItem30,gotItem31,gotItem32,gotItem33,gotItem34,gotItem35,gotItem36,gotItem37,gotItem38,gotItem39,gotItem40,gotItem41,gotItem42,gotItem43,gotItem44,gotItem45,gotItem46,gotItem47,gotItem48,gotItem49,gotItem50,gotItem51,gotItem52,gotItem53,gotItem54,gotItem55,gotItem56,gotItem57,gotItem58;
@synthesize introducedToKingV, gotOrb, killedBugs;
@synthesize beatIonak,acceptedMessageKingK,acceptedTaskTraveler,acceptedFindEilifKingV,acceptedTaskKingVPostOrb,deliveredLetterToKingK,hasLitOrb,toldNewsKingV,talkedToKingVInitial,talkedToKingVPostOrb,finishedTaskTraveler;
@synthesize beatDragon,beatCyclops,beatCaveBoss,talkedToArnuk,talkedToEilif,savedKing;
@synthesize gotPrizeFromKingV,gotRepellent;
@synthesize sprite1position;
@synthesize heroAtkStyle,gotFireRoot;
@synthesize talkedToEilifPostBoss;
@synthesize talkedToWatchmen,usedBook;
@synthesize attribGoldMult,attribExpMult;


@synthesize heroCurrentHP;
@synthesize gold, exp, heroHP, heroStr, defBonus, heroName, position, strBonus, currentMap, freePoints, heroStrDef, heroInventory, heroOrientation, heroLvl;
@synthesize heroSPD;
@synthesize attributePoints;

@synthesize aglBonus, defMult, strMult, aglMult;

@synthesize equipPos1,equipPos2,equipPos3,equipPos4,equipPos5,equipPos6;

@synthesize attrib1,attrib2,attrib3,attrib4,attrib5,attrib6,attrib7,attrib8,attrib9,attrib10,attrib11,attrib12,attrib13,attrib14,attrib15,attrib16,attrib17,attrib18,attrib19;

@synthesize attribAgiMult,attribDefMult,attribStrMult;

@synthesize itemInPos1,itemInPos2,itemInPos3,itemInPos4,itemInPos5,itemInPos6;

@synthesize itemExpMult;
@synthesize itemGoldMult;

@synthesize mapInitMode;
@synthesize musicCode;

@synthesize sprite2position,sprite3position,sprite4position,sprite5position,sprite6position,sprite7position,sprite8position,sprite9position,sprite10position,sprite11position,sprite12position,sprite13position,sprite14position,sprite15position,sprite16position,sprite17position,sprite18position,sprite19position,sprite20position,sprite21position,sprite22position,sprite23position,sprite24position,sprite25position,sprite26position,sprite27position;

@synthesize sprite1_Orientation,sprite2_Orientation,sprite3_Orientation,sprite4_Orientation,sprite5_Orientation,sprite6_Orientation,sprite7_Orientation,sprite8_Orientation,sprite9_Orientation,sprite10_Orientation,sprite11_Orientation,sprite12_Orientation,sprite13_Orientation,sprite14_Orientation,sprite15_Orientation,sprite16_Orientation,sprite17_Orientation,sprite18_Orientation,sprite19_Orientation,sprite20_Orientation,sprite21_Orientation,sprite22_Orientation,sprite23_Orientation,sprite24_Orientation,sprite25_Orientation,sprite26_Orientation,sprite27_Orientation;

@synthesize sprite30_Orientation,sprite30position,sprite31_Orientation,sprite31position,sprite32_Orientation,sprite32position,sprite33_Orientation,sprite33position,sprite34_Orientation,sprite34position,sprite35_Orientation,sprite35position,sprite36_Orientation,sprite36position,sprite37_Orientation,sprite37position,sprite38_Orientation,sprite38position,sprite39_Orientation,sprite39position,sprite40_Orientation,sprite40position,sprite41_Orientation,sprite41position,sprite42_Orientation,sprite42position,sprite43_Orientation,sprite43position,sprite44_Orientation,sprite44position,sprite45_Orientation,sprite45position,sprite46_Orientation,sprite46position,sprite47_Orientation,sprite47position,sprite48_Orientation,sprite48position,sprite49_Orientation,sprite49position,sprite50_Orientation,sprite50position,sprite51_Orientation,sprite51position,sprite52_Orientation,sprite52position,sprite53_Orientation,sprite53position;

@synthesize sprite61_Orientation,sprite61position,sprite62_Orientation,sprite62position,sprite63_Orientation,sprite63position,sprite64_Orientation,sprite64position,sprite65_Orientation,sprite65position,sprite66_Orientation,sprite66position,sprite67_Orientation,sprite67position,sprite68_Orientation,sprite68position,sprite69_Orientation,sprite69position,sprite70_Orientation,sprite70position,sprite71_Orientation,sprite71position,sprite72_Orientation,sprite72position,sprite73_Orientation,sprite73position,sprite74_Orientation,sprite74position,sprite75_Orientation,sprite75position,sprite76_Orientation,sprite76position;

@synthesize beatVank,beatTitan,beatVodek,beatCaveTroll,beatIceGolem1,beatIceGolem2,beatIceGolem3,beatSunDragon;
@synthesize beatTowerKeeper, gotEarthSword;

@synthesize beatTraveler,sprite100_Orientation,sprite100position,sprite101_Orientation,sprite101position,sprite102_Orientation,sprite102position,sprite103_Orientation,sprite103position,sprite104_Orientation,sprite104position,sprite81_Orientation,sprite81position,sprite82_Orientation,sprite82position,sprite83_Orientation,sprite83position,sprite84_Orientation,sprite84position,sprite85_Orientation,sprite85position,sprite86_Orientation,sprite86position,sprite87_Orientation,sprite87position,sprite88_Orientation,sprite88position,sprite89_Orientation,sprite89position,sprite90_Orientation,sprite90position,sprite91_Orientation,sprite91position,sprite92_Orientation,sprite92position,sprite93_Orientation,sprite93position,sprite94_Orientation,sprite94position,sprite95_Orientation,sprite95position,sprite96_Orientation,sprite96position,sprite97_Orientation,sprite97position,sprite98_Orientation,sprite98position,sprite99_Orientation,sprite99position;

@synthesize sprite111_Orientation,sprite111position,sprite112_Orientation,sprite112position,sprite113_Orientation,sprite113position,sprite114_Orientation,sprite114position,sprite115_Orientation,sprite115position,sprite116_Orientation,sprite116position,sprite117_Orientation,sprite117position,sprite118_Orientation,sprite118position,sprite119_Orientation,sprite119position;

@synthesize sprite120_Orientation,sprite120position,sprite121_Orientation,sprite121position,sprite122_Orientation,sprite122position,sprite123_Orientation,sprite123position,sprite124_Orientation,sprite124position,sprite125_Orientation,sprite125position,sprite126_Orientation,sprite126position,sprite127_Orientation,sprite127position,sprite128_Orientation,sprite128position,sprite129_Orientation,sprite129position,sprite130_Orientation,sprite130position;

@synthesize gotItem59,gotItem60,gotItem61,gotItem62,gotItem63;

@synthesize isRainingPL1,isRainingPL3,isRainingPL4,isSnowingPL6;

- (id)init {
    self = [super init];
    if (self) {
        
        //Do Nothing
        
        //Let GameSceneManager initialize Hero
    }
    return self;
}

- (id)initWithCoder:(NSCoder *)decoder {
    self = [super init];
    if(self) {
        if (![decoder decodeObjectForKey:@"freeSteps"])
            return nil;
        
        self.beatBoss1 = [decoder decodeBoolForKey:@"beatBoss1"];
        self.freeSteps = [decoder decodeIntForKey:@"freeSteps"];
        self.wentEllemakPostSaveKing = [decoder decodeBoolForKey:@"wentEllemakPostSaveKing"];
        self.wentEllemakPostBeatIonak = [decoder decodeBoolForKey:@"wentEllemakPostBeatIonak"];
        
        self.gotItem1 = [decoder decodeBoolForKey:@"gotItem1"];
        self.gotItem2 = [decoder decodeBoolForKey:@"gotItem2"];
        self.gotItem3 = [decoder decodeBoolForKey:@"gotItem3"];
        self.gotItem4 = [decoder decodeBoolForKey:@"gotItem4"];
        self.gotItem5 = [decoder decodeBoolForKey:@"gotItem5"];
        self.gotItem6 = [decoder decodeBoolForKey:@"gotItem6"];
        self.gotItem7 = [decoder decodeBoolForKey:@"gotItem7"];
        self.gotItem8 = [decoder decodeBoolForKey:@"gotItem8"];
        self.gotItem9 = [decoder decodeBoolForKey:@"gotItem9"];
        self.gotItem10 = [decoder decodeBoolForKey:@"gotItem10"];
        self.gotItem11 = [decoder decodeBoolForKey:@"gotItem11"];
        self.gotItem12 = [decoder decodeBoolForKey:@"gotItem12"];
        self.gotItem13 = [decoder decodeBoolForKey:@"gotItem13"];
        self.gotItem14 = [decoder decodeBoolForKey:@"gotItem14"];
        self.gotItem15 = [decoder decodeBoolForKey:@"gotItem15"];
        self.gotItem16 = [decoder decodeBoolForKey:@"gotItem16"];
        self.gotItem17 = [decoder decodeBoolForKey:@"gotItem17"];
        self.gotItem18 = [decoder decodeBoolForKey:@"gotItem18"];
        self.gotItem19 = [decoder decodeBoolForKey:@"gotItem19"];
        self.gotItem20 = [decoder decodeBoolForKey:@"gotItem20"];
        self.gotItem21 = [decoder decodeBoolForKey:@"gotItem21"];
        self.gotItem22 = [decoder decodeBoolForKey:@"gotItem22"];
        self.gotItem23 = [decoder decodeBoolForKey:@"gotItem23"];
        self.gotItem24 = [decoder decodeBoolForKey:@"gotItem24"];
        self.gotItem25 = [decoder decodeBoolForKey:@"gotItem25"];
        self.gotItem26 = [decoder decodeBoolForKey:@"gotItem26"];
        self.gotItem27 = [decoder decodeBoolForKey:@"gotItem27"];
        self.gotItem28 = [decoder decodeBoolForKey:@"gotItem28"];
        self.gotItem29 = [decoder decodeBoolForKey:@"gotItem29"];
        self.gotItem30 = [decoder decodeBoolForKey:@"gotItem30"];
        self.gotItem31 = [decoder decodeBoolForKey:@"gotItem31"];
        self.gotItem32 = [decoder decodeBoolForKey:@"gotItem32"];
        self.gotItem33 = [decoder decodeBoolForKey:@"gotItem33"];
        self.gotItem34 = [decoder decodeBoolForKey:@"gotItem34"];
        self.gotItem35 = [decoder decodeBoolForKey:@"gotItem35"];
        self.gotItem36 = [decoder decodeBoolForKey:@"gotItem36"];
        self.gotItem37 = [decoder decodeBoolForKey:@"gotItem37"];
        self.gotItem38 = [decoder decodeBoolForKey:@"gotItem38"];
        self.gotItem39 = [decoder decodeBoolForKey:@"gotItem39"];
        self.gotItem40 = [decoder decodeBoolForKey:@"gotItem40"];
        self.gotItem41 = [decoder decodeBoolForKey:@"gotItem41"];
        self.gotItem42 = [decoder decodeBoolForKey:@"gotItem42"];
        self.gotItem43 = [decoder decodeBoolForKey:@"gotItem43"];
        self.gotItem44 = [decoder decodeBoolForKey:@"gotItem44"];
        self.gotItem45 = [decoder decodeBoolForKey:@"gotItem45"];
        self.gotItem46 = [decoder decodeBoolForKey:@"gotItem46"];
        self.gotItem47 = [decoder decodeBoolForKey:@"gotItem47"];
        self.gotItem48 = [decoder decodeBoolForKey:@"gotItem48"];
        self.gotItem49 = [decoder decodeBoolForKey:@"gotItem49"];
        self.gotItem50 = [decoder decodeBoolForKey:@"gotItem50"];
        self.gotItem51 = [decoder decodeBoolForKey:@"gotItem51"];
        self.gotItem52 = [decoder decodeBoolForKey:@"gotItem52"];
        self.gotItem53 = [decoder decodeBoolForKey:@"gotItem53"];
        self.gotItem54 = [decoder decodeBoolForKey:@"gotItem54"];
        self.gotItem55 = [decoder decodeBoolForKey:@"gotItem55"];
        self.gotItem56 = [decoder decodeBoolForKey:@"gotItem56"];
        self.gotItem57 = [decoder decodeBoolForKey:@"gotItem57"];
        self.gotItem58 = [decoder decodeBoolForKey:@"gotItem58"];
        
        self.gotLorica = [decoder decodeBoolForKey:@"gotLorica"];
        self.introducedToKingV = [decoder decodeBoolForKey:@"introducedToKingV"];
        self.gotOrb = [decoder decodeBoolForKey:@"gotOrb"];
        self.killedBugs = [decoder decodeBoolForKey:@"killedBugs"];
        self.beatIonak = [decoder decodeBoolForKey:@"beatIonak"];
        self.acceptedMessageKingK = [decoder decodeBoolForKey:@"acceptedMessageKingK"];
        self.acceptedTaskTraveler = [decoder decodeBoolForKey:@"acceptedTaskTraveler"];
        self.acceptedFindEilifKingV = [decoder decodeBoolForKey:@"acceptedFindEilifKingV"];
        self.acceptedTaskKingVPostOrb = [decoder decodeBoolForKey:@"acceptedTaskKingVPostOrb"];
        self.deliveredLetterToKingK = [decoder decodeBoolForKey:@"deliveredLetterToKingK"];
        self.hasLitOrb = [decoder decodeBoolForKey:@"hasLitOrb"];
        self.toldNewsKingV = [decoder decodeBoolForKey:@"toldNewsKingV"];
        self.talkedToKingVInitial = [decoder decodeBoolForKey:@"talkedToKingVInitial"];
        self.talkedToKingVPostOrb = [decoder decodeBoolForKey:@"talkedToKingVPostOrb"];
        self.finishedTaskTraveler = [decoder decodeBoolForKey:@"finishedTaskTraveler"];
        self.beatDragon = [decoder decodeBoolForKey:@"beatDragon"];
        self.beatCyclops = [decoder decodeBoolForKey:@"beatCyclops"];
        self.beatCaveBoss = [decoder decodeBoolForKey:@"beatCaveBoss"];
        self.talkedToArnuk = [decoder decodeBoolForKey:@"talkedToArnuk"];
        self.talkedToEilif = [decoder decodeBoolForKey:@"talkedToEilif"];
        self.savedKing = [decoder decodeBoolForKey:@"savedKing"];
        self.gotPrizeFromKingV = [decoder decodeBoolForKey:@"gotPrizeFromKingV"];
        self.gotRepellent = [decoder decodeBoolForKey:@"gotRepellent"];
        
        CGPoint tempPoint = CGPointMake(0, 0);
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite1position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite1position.y"];
        self.sprite1position = tempPoint;

        self.heroAtkStyle = [decoder decodeIntForKey:@"heroAtkStyle"];
        self.gotFireRoot = [decoder decodeBoolForKey:@"gotFireRoot"];
        self.talkedToEilifPostBoss = [decoder decodeBoolForKey:@"talkedToEilifPostBoss"];
        self.talkedToWatchmen = [decoder decodeBoolForKey:@"talkedToWatchmen"];
        self.usedBook = [decoder decodeBoolForKey:@"usedBook"];
        self.attribGoldMult = [decoder decodeDoubleForKey:@"attribGoldMult"];
        self.attribExpMult = [decoder decodeDoubleForKey:@"attribExpMult"];
        
        self.heroCurrentHP = [decoder decodeIntForKey:@"heroCurrentHP"];
        self.gold = [decoder decodeIntForKey:@"gold"];
        self.exp = [decoder decodeIntForKey:@"exp"];
        self.heroHP = [decoder decodeIntForKey:@"heroHP"];
        self.heroStr = [decoder decodeIntForKey:@"heroStr"];
        self.defBonus = [decoder decodeIntForKey:@"defBonus"];
        self.heroName = [decoder decodeObjectForKey:@"heroName"];
        
        tempPoint.x = [decoder decodeDoubleForKey:@"position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"position.y"];
        self.position = tempPoint;
        
        self.strBonus = [decoder decodeIntForKey:@"strBonus"];
        self.currentMap = [decoder decodeIntForKey:@"currentMap"];
        self.freePoints = [decoder decodeIntForKey:@"freePoints"];
        self.heroStrDef = [decoder decodeIntForKey:@"heroStrDef"];
        
        NSData *dataRepresentingSavedArray = [decoder decodeObjectForKey:@"heroInventory"];
        if (dataRepresentingSavedArray != nil)
        {
            NSArray *oldSavedArray = [NSKeyedUnarchiver unarchiveObjectWithData:dataRepresentingSavedArray];
            if (oldSavedArray != nil)
                self.heroInventory = [[NSMutableArray alloc] initWithArray:oldSavedArray];
            else
                self.heroInventory = [[NSMutableArray alloc] init];
        }
        
        self.heroOrientation = [decoder decodeIntForKey:@"heroOrientation"];
        self.heroLvl = [decoder decodeIntForKey:@"heroLvl"];
        self.heroSPD = [decoder decodeIntForKey:@"heroSPD"];
        self.attributePoints = [decoder decodeIntForKey:@"attributePoints"];
        self.aglBonus = [decoder decodeIntForKey:@"aglBonus"];
        self.defMult = [decoder decodeDoubleForKey:@"defMult"];
        self.strMult = [decoder decodeDoubleForKey:@"strMult"];
        self.aglMult = [decoder decodeDoubleForKey:@"aglMult"];
        
        self.equipPos1 = [decoder decodeObjectForKey:@"equipPos1"];
        self.equipPos2 = [decoder decodeObjectForKey:@"equipPos2"];
        self.equipPos3 = [decoder decodeObjectForKey:@"equipPos3"];
        self.equipPos4 = [decoder decodeObjectForKey:@"equipPos4"];
        self.equipPos5 = [decoder decodeObjectForKey:@"equipPos5"];
        self.equipPos6 = [decoder decodeObjectForKey:@"equipPos6"];
        
        self.attrib1 = [decoder decodeBoolForKey:@"attrib1"];
        self.attrib2 = [decoder decodeBoolForKey:@"attrib2"];
        self.attrib3 = [decoder decodeBoolForKey:@"attrib3"];
        self.attrib4 = [decoder decodeBoolForKey:@"attrib4"];
        self.attrib5 = [decoder decodeBoolForKey:@"attrib5"];
        self.attrib6 = [decoder decodeBoolForKey:@"attrib6"];
        self.attrib7 = [decoder decodeBoolForKey:@"attrib7"];
        self.attrib8 = [decoder decodeBoolForKey:@"attrib8"];
        self.attrib9 = [decoder decodeBoolForKey:@"attrib9"];
        self.attrib10 = [decoder decodeBoolForKey:@"attrib10"];
        self.attrib11 = [decoder decodeBoolForKey:@"attrib11"];
        self.attrib12 = [decoder decodeBoolForKey:@"attrib12"];
        self.attrib13 = [decoder decodeBoolForKey:@"attrib13"];
        self.attrib14 = [decoder decodeBoolForKey:@"attrib14"];
        self.attrib15 = [decoder decodeBoolForKey:@"attrib15"];
        self.attrib16 = [decoder decodeBoolForKey:@"attrib16"];
        self.attrib17 = [decoder decodeBoolForKey:@"attrib17"];
        self.attrib18 = [decoder decodeBoolForKey:@"attrib18"];
        self.attrib19 = [decoder decodeBoolForKey:@"attrib19"];
        
        self.attribAgiMult = [decoder decodeDoubleForKey:@"attribAgiMult"];
        self.attribDefMult = [decoder decodeDoubleForKey:@"attribDefMult"];
        self.attribStrMult = [decoder decodeDoubleForKey:@"attribStrMult"];
        
        self.itemInPos1 = [decoder decodeBoolForKey:@"itemInPos1"];
        self.itemInPos2 = [decoder decodeBoolForKey:@"itemInPos2"];
        self.itemInPos3 = [decoder decodeBoolForKey:@"itemInPos3"];
        self.itemInPos4 = [decoder decodeBoolForKey:@"itemInPos4"];
        self.itemInPos5 = [decoder decodeBoolForKey:@"itemInPos5"];
        self.itemInPos6 = [decoder decodeBoolForKey:@"itemInPos6"];
        
        self.itemExpMult = [decoder decodeDoubleForKey:@"itemExpMult"];
        self.itemGoldMult = [decoder decodeDoubleForKey:@"itemGoldMult"];
        
        self.mapInitMode = [decoder decodeIntForKey:@"mapInitMode"];
        self.musicCode = [decoder decodeIntForKey:@"musicCode"];
        
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite2position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite2position.y"];
        self.sprite2position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite3position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite3position.y"];
        self.sprite3position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite4position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite4position.y"];
        self.sprite4position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite5position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite5position.y"];
        self.sprite5position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite6position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite6position.y"];
        self.sprite6position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite7position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite7position.y"];
        self.sprite7position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite8position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite8position.y"];
        self.sprite8position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite9position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite9position.y"];
        self.sprite9position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite10position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite10position.y"];
        self.sprite10position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite11position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite11position.y"];
        self.sprite11position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite12position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite12position.y"];
        self.sprite12position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite13position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite13position.y"];
        self.sprite13position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite14position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite14position.y"];
        self.sprite14position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite15position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite15position.y"];
        self.sprite15position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite16position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite16position.y"];
        self.sprite16position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite17position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite17position.y"];
        self.sprite17position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite18position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite18position.y"];
        self.sprite18position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite19position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite19position.y"];
        self.sprite19position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite20position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite20position.y"];
        self.sprite20position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite21position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite21position.y"];
        self.sprite21position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite22position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite22position.y"];
        self.sprite22position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite23position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite23position.y"];
        self.sprite23position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite24position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite24position.y"];
        self.sprite24position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite25position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite25position.y"];
        self.sprite25position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite26position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite26position.y"];
        self.sprite26position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite27position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite27position.y"];
        self.sprite27position = tempPoint;
        
        self.sprite1_Orientation = [decoder decodeIntForKey:@"sprite1_Orientation"];
        self.sprite2_Orientation = [decoder decodeIntForKey:@"sprite2_Orientation"];
        self.sprite3_Orientation = [decoder decodeIntForKey:@"sprite3_Orientation"];
        self.sprite4_Orientation = [decoder decodeIntForKey:@"sprite4_Orientation"];
        self.sprite5_Orientation = [decoder decodeIntForKey:@"sprite5_Orientation"];
        self.sprite6_Orientation = [decoder decodeIntForKey:@"sprite6_Orientation"];
        self.sprite7_Orientation = [decoder decodeIntForKey:@"sprite7_Orientation"];
        self.sprite8_Orientation = [decoder decodeIntForKey:@"sprite8_Orientation"];
        self.sprite9_Orientation = [decoder decodeIntForKey:@"sprite9_Orientation"];
        self.sprite10_Orientation = [decoder decodeIntForKey:@"sprite10_Orientation"];
        self.sprite11_Orientation = [decoder decodeIntForKey:@"sprite11_Orientation"];
        self.sprite12_Orientation = [decoder decodeIntForKey:@"sprite12_Orientation"];
        self.sprite13_Orientation = [decoder decodeIntForKey:@"sprite13_Orientation"];
        self.sprite14_Orientation = [decoder decodeIntForKey:@"sprite14_Orientation"];
        self.sprite15_Orientation = [decoder decodeIntForKey:@"sprite15_Orientation"];
        self.sprite16_Orientation = [decoder decodeIntForKey:@"sprite16_Orientation"];
        self.sprite17_Orientation = [decoder decodeIntForKey:@"sprite17_Orientation"];
        self.sprite18_Orientation = [decoder decodeIntForKey:@"sprite18_Orientation"];
        self.sprite19_Orientation = [decoder decodeIntForKey:@"sprite19_Orientation"];
        self.sprite20_Orientation = [decoder decodeIntForKey:@"sprite20_Orientation"];
        self.sprite21_Orientation = [decoder decodeIntForKey:@"sprite21_Orientation"];
        self.sprite22_Orientation = [decoder decodeIntForKey:@"sprite22_Orientation"];
        self.sprite23_Orientation = [decoder decodeIntForKey:@"sprite23_Orientation"];
        self.sprite24_Orientation = [decoder decodeIntForKey:@"sprite24_Orientation"];
        self.sprite25_Orientation = [decoder decodeIntForKey:@"sprite25_Orientation"];
        self.sprite26_Orientation = [decoder decodeIntForKey:@"sprite26_Orientation"];
        self.sprite27_Orientation = [decoder decodeIntForKey:@"sprite27_Orientation"];
        
        self.sprite30_Orientation = [decoder decodeIntForKey:@"sprite30_Orientation"];
        self.sprite31_Orientation = [decoder decodeIntForKey:@"sprite31_Orientation"];
        self.sprite32_Orientation = [decoder decodeIntForKey:@"sprite32_Orientation"];
        self.sprite33_Orientation = [decoder decodeIntForKey:@"sprite33_Orientation"];
        self.sprite34_Orientation = [decoder decodeIntForKey:@"sprite34_Orientation"];
        self.sprite35_Orientation = [decoder decodeIntForKey:@"sprite35_Orientation"];
        self.sprite36_Orientation = [decoder decodeIntForKey:@"sprite36_Orientation"];
        self.sprite37_Orientation = [decoder decodeIntForKey:@"sprite37_Orientation"];
        self.sprite38_Orientation = [decoder decodeIntForKey:@"sprite38_Orientation"];
        self.sprite39_Orientation = [decoder decodeIntForKey:@"sprite39_Orientation"];
        self.sprite40_Orientation = [decoder decodeIntForKey:@"sprite40_Orientation"];
        self.sprite41_Orientation = [decoder decodeIntForKey:@"sprite41_Orientation"];
        self.sprite42_Orientation = [decoder decodeIntForKey:@"sprite42_Orientation"];
        self.sprite43_Orientation = [decoder decodeIntForKey:@"sprite43_Orientation"];
        self.sprite44_Orientation = [decoder decodeIntForKey:@"sprite44_Orientation"];
        self.sprite45_Orientation = [decoder decodeIntForKey:@"sprite45_Orientation"];
        self.sprite46_Orientation = [decoder decodeIntForKey:@"sprite46_Orientation"];
        self.sprite47_Orientation = [decoder decodeIntForKey:@"sprite47_Orientation"];
        self.sprite48_Orientation = [decoder decodeIntForKey:@"sprite48_Orientation"];
        self.sprite49_Orientation = [decoder decodeIntForKey:@"sprite49_Orientation"];
        self.sprite50_Orientation = [decoder decodeIntForKey:@"sprite50_Orientation"];
        self.sprite51_Orientation = [decoder decodeIntForKey:@"sprite51_Orientation"];
        self.sprite52_Orientation = [decoder decodeIntForKey:@"sprite52_Orientation"];
        self.sprite53_Orientation = [decoder decodeIntForKey:@"sprite53_Orientation"];
        
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite30position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite30position.y"];
        self.sprite30position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite31position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite31position.y"];
        self.sprite31position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite32position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite32position.y"];
        self.sprite32position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite33position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite33position.y"];
        self.sprite33position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite34position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite34position.y"];
        self.sprite34position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite35position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite35position.y"];
        self.sprite35position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite36position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite36position.y"];
        self.sprite36position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite37position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite37position.y"];
        self.sprite37position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite38position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite38position.y"];
        self.sprite38position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite39position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite39position.y"];
        self.sprite39position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite40position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite40position.y"];
        self.sprite40position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite41position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite41position.y"];
        self.sprite41position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite42position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite42position.y"];
        self.sprite42position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite43position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite43position.y"];
        self.sprite43position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite44position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite44position.y"];
        self.sprite44position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite45position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite45position.y"];
        self.sprite45position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite46position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite46position.y"];
        self.sprite46position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite47position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite47position.y"];
        self.sprite47position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite48position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite48position.y"];
        self.sprite48position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite49position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite49position.y"];
        self.sprite49position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite50position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite50position.y"];
        self.sprite50position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite51position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite51position.y"];
        self.sprite51position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite52position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite52position.y"];
        self.sprite52position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite53position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite53position.y"];
        self.sprite53position = tempPoint;

        self.sprite61_Orientation = [decoder decodeIntForKey:@"sprite61_Orientation"];
        self.sprite62_Orientation = [decoder decodeIntForKey:@"sprite62_Orientation"];
        self.sprite63_Orientation = [decoder decodeIntForKey:@"sprite63_Orientation"];
        self.sprite64_Orientation = [decoder decodeIntForKey:@"sprite64_Orientation"];
        self.sprite65_Orientation = [decoder decodeIntForKey:@"sprite65_Orientation"];
        self.sprite66_Orientation = [decoder decodeIntForKey:@"sprite66_Orientation"];
        self.sprite67_Orientation = [decoder decodeIntForKey:@"sprite67_Orientation"];
        self.sprite68_Orientation = [decoder decodeIntForKey:@"sprite68_Orientation"];
        self.sprite69_Orientation = [decoder decodeIntForKey:@"sprite69_Orientation"];
        self.sprite70_Orientation = [decoder decodeIntForKey:@"sprite70_Orientation"];
        self.sprite71_Orientation = [decoder decodeIntForKey:@"sprite71_Orientation"];
        self.sprite72_Orientation = [decoder decodeIntForKey:@"sprite72_Orientation"];
        self.sprite73_Orientation = [decoder decodeIntForKey:@"sprite73_Orientation"];
        self.sprite74_Orientation = [decoder decodeIntForKey:@"sprite74_Orientation"];
        self.sprite75_Orientation = [decoder decodeIntForKey:@"sprite75_Orientation"];
        self.sprite76_Orientation = [decoder decodeIntForKey:@"sprite76_Orientation"];
        
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite61position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite61position.y"];
        self.sprite61position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite62position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite62position.y"];
        self.sprite62position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite63position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite63position.y"];
        self.sprite63position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite64position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite64position.y"];
        self.sprite64position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite65position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite65position.y"];
        self.sprite65position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite66position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite66position.y"];
        self.sprite66position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite67position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite67position.y"];
        self.sprite67position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite68position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite68position.y"];
        self.sprite68position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite69position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite69position.y"];
        self.sprite69position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite70position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite70position.y"];
        self.sprite70position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite71position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite71position.y"];
        self.sprite71position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite72position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite72position.y"];
        self.sprite72position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite73position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite73position.y"];
        self.sprite73position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite74position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite74position.y"];
        self.sprite74position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite75position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite75position.y"];
        self.sprite75position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite76position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite76position.y"];
        self.sprite76position = tempPoint;
        
        self.beatVank = [decoder decodeBoolForKey:@"beatVank"];
        self.beatTitan = [decoder decodeBoolForKey:@"beatTitan"];
        self.beatCaveTroll = [decoder decodeBoolForKey:@"beatCaveTroll"];
        self.beatIceGolem1 = [decoder decodeBoolForKey:@"beatIceGolem1"];
        self.beatIceGolem2 = [decoder decodeBoolForKey:@"beatIceGolem2"];
        self.beatIceGolem3 = [decoder decodeBoolForKey:@"beatIceGolem3"];
        self.beatSunDragon = [decoder decodeBoolForKey:@"beatSunDragon"];
        self.beatTowerKeeper = [decoder decodeBoolForKey:@"beatTowerKeeper"];
        self.gotEarthSword = [decoder decodeBoolForKey:@"gotEarthSword"];
        self.beatTraveler = [decoder decodeBoolForKey:@"beatTraveler"];
        
        self.sprite81_Orientation = [decoder decodeIntForKey:@"sprite81_Orientation"];
        self.sprite82_Orientation = [decoder decodeIntForKey:@"sprite82_Orientation"];
        self.sprite83_Orientation = [decoder decodeIntForKey:@"sprite83_Orientation"];
        self.sprite84_Orientation = [decoder decodeIntForKey:@"sprite84_Orientation"];
        self.sprite85_Orientation = [decoder decodeIntForKey:@"sprite85_Orientation"];
        self.sprite86_Orientation = [decoder decodeIntForKey:@"sprite86_Orientation"];
        self.sprite87_Orientation = [decoder decodeIntForKey:@"sprite87_Orientation"];
        self.sprite88_Orientation = [decoder decodeIntForKey:@"sprite88_Orientation"];
        self.sprite89_Orientation = [decoder decodeIntForKey:@"sprite89_Orientation"];
        self.sprite90_Orientation = [decoder decodeIntForKey:@"sprite90_Orientation"];
        self.sprite91_Orientation = [decoder decodeIntForKey:@"sprite91_Orientation"];
        self.sprite92_Orientation = [decoder decodeIntForKey:@"sprite92_Orientation"];
        self.sprite93_Orientation = [decoder decodeIntForKey:@"sprite93_Orientation"];
        self.sprite94_Orientation = [decoder decodeIntForKey:@"sprite94_Orientation"];
        self.sprite95_Orientation = [decoder decodeIntForKey:@"sprite95_Orientation"];
        self.sprite96_Orientation = [decoder decodeIntForKey:@"sprite96_Orientation"];
        self.sprite97_Orientation = [decoder decodeIntForKey:@"sprite97_Orientation"];
        self.sprite98_Orientation = [decoder decodeIntForKey:@"sprite98_Orientation"];
        self.sprite99_Orientation = [decoder decodeIntForKey:@"sprite99_Orientation"];
        self.sprite100_Orientation = [decoder decodeIntForKey:@"sprite100_Orientation"];
        self.sprite101_Orientation = [decoder decodeIntForKey:@"sprite101_Orientation"];
        self.sprite102_Orientation = [decoder decodeIntForKey:@"sprite102_Orientation"];
        self.sprite103_Orientation = [decoder decodeIntForKey:@"sprite103_Orientation"];
        self.sprite104_Orientation = [decoder decodeIntForKey:@"sprite104_Orientation"];
        
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite81position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite81position.y"];
        self.sprite81position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite82position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite82position.y"];
        self.sprite82position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite83position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite83position.y"];
        self.sprite83position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite84position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite84position.y"];
        self.sprite84position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite85position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite85position.y"];
        self.sprite85position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite88position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite88position.y"];
        self.sprite88position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite87position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite87position.y"];
        self.sprite87position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite88position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite88position.y"];
        self.sprite88position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite89position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite89position.y"];
        self.sprite89position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite90position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite90position.y"];
        self.sprite90position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite91position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite91position.y"];
        self.sprite91position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite92position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite92position.y"];
        self.sprite92position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite93position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite93position.y"];
        self.sprite93position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite94position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite94position.y"];
        self.sprite94position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite95position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite95position.y"];
        self.sprite95position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite96position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite96position.y"];
        self.sprite96position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite97position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite97position.y"];
        self.sprite97position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite98position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite98position.y"];
        self.sprite98position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite99position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite99position.y"];
        self.sprite99position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite100position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite100position.y"];
        self.sprite100position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite101position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite101position.y"];
        self.sprite101position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite102position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite102position.y"];
        self.sprite102position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite103position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite103position.y"];
        self.sprite103position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite104position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite104position.y"];
        self.sprite104position = tempPoint;
        
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite111position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite111position.y"];
        self.sprite111position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite112position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite112position.y"];
        self.sprite112position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite113position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite113position.y"];
        self.sprite113position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite114position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite114position.y"];
        self.sprite114position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite115position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite115position.y"];
        self.sprite115position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite116position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite116position.y"];
        self.sprite116position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite117position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite117position.y"];
        self.sprite117position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite118position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite118position.y"];
        self.sprite118position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite119position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite119position.y"];
        self.sprite119position = tempPoint;
        
        self.sprite111_Orientation = [decoder decodeIntForKey:@"sprite111_Orientation"];
        self.sprite112_Orientation = [decoder decodeIntForKey:@"sprite112_Orientation"];
        self.sprite113_Orientation = [decoder decodeIntForKey:@"sprite113_Orientation"];
        self.sprite114_Orientation = [decoder decodeIntForKey:@"sprite114_Orientation"];
        self.sprite115_Orientation = [decoder decodeIntForKey:@"sprite115_Orientation"];
        self.sprite116_Orientation = [decoder decodeIntForKey:@"sprite116_Orientation"];
        self.sprite117_Orientation = [decoder decodeIntForKey:@"sprite117_Orientation"];
        self.sprite118_Orientation = [decoder decodeIntForKey:@"sprite118_Orientation"];
        self.sprite119_Orientation = [decoder decodeIntForKey:@"sprite119_Orientation"];
        
        self.sprite120_Orientation = [decoder decodeIntForKey:@"sprite120_Orientation"];
        self.sprite121_Orientation = [decoder decodeIntForKey:@"sprite121_Orientation"];
        self.sprite122_Orientation = [decoder decodeIntForKey:@"sprite122_Orientation"];
        self.sprite123_Orientation = [decoder decodeIntForKey:@"sprite123_Orientation"];
        self.sprite124_Orientation = [decoder decodeIntForKey:@"sprite124_Orientation"];
        self.sprite125_Orientation = [decoder decodeIntForKey:@"sprite125_Orientation"];
        self.sprite126_Orientation = [decoder decodeIntForKey:@"sprite126_Orientation"];
        self.sprite127_Orientation = [decoder decodeIntForKey:@"sprite127_Orientation"];
        self.sprite128_Orientation = [decoder decodeIntForKey:@"sprite128_Orientation"];
        self.sprite129_Orientation = [decoder decodeIntForKey:@"sprite129_Orientation"];
        self.sprite130_Orientation = [decoder decodeIntForKey:@"sprite130_Orientation"];
        
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite120position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite120position.y"];
        self.sprite120position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite121position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite121position.y"];
        self.sprite121position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite122position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite122position.y"];
        self.sprite122position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite123position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite123position.y"];
        self.sprite123position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite124position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite124position.y"];
        self.sprite124position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite125position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite125position.y"];
        self.sprite125position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite126position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite126position.y"];
        self.sprite126position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite127position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite127position.y"];
        self.sprite127position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite128position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite128position.y"];
        self.sprite128position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite129position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite129position.y"];
        self.sprite129position = tempPoint;
        tempPoint.x = [decoder decodeDoubleForKey:@"sprite130position.x"];
        tempPoint.y = [decoder decodeDoubleForKey:@"sprite130position.y"];
        self.sprite130position = tempPoint;
        
        self.gotItem59 = [decoder decodeBoolForKey:@"gotItem59"];
        self.gotItem60 = [decoder decodeBoolForKey:@"gotItem60"];
        self.gotItem61 = [decoder decodeBoolForKey:@"gotItem61"];
        self.gotItem62 = [decoder decodeBoolForKey:@"gotItem62"];
        self.gotItem63 = [decoder decodeBoolForKey:@"gotItem63"];
        
        self.isRainingPL1 = [decoder decodeBoolForKey:@"isRainingPL1"];
        self.isRainingPL3 = [decoder decodeBoolForKey:@"isRainingPL3"];
        self.isRainingPL4 = [decoder decodeBoolForKey:@"isRainingPL4"];
        self.isSnowingPL6 = [decoder decodeBoolForKey:@"isSnowingPL6"];
    }
    return self;
}


- (void)encodeWithCoder:(NSCoder *)encoder {
    
    [encoder encodeBool:self.beatBoss1 forKey:@"beatBoss1"];
    [encoder encodeBool:self.freeSteps forKey:@"freeSteps"];
    [encoder encodeBool:self.wentEllemakPostSaveKing forKey:@"wentEllemakPostSaveKing"];
    [encoder encodeBool:self.wentEllemakPostBeatIonak forKey:@"wentEllemakPostBeatIonak"];
    
    [encoder encodeBool:self.gotItem1 forKey:@"gotItem1"];
    [encoder encodeBool:self.gotItem2 forKey:@"gotItem2"];
    [encoder encodeBool:self.gotItem3 forKey:@"gotItem3"];
    [encoder encodeBool:self.gotItem4 forKey:@"gotItem4"];
    [encoder encodeBool:self.gotItem5 forKey:@"gotItem5"];
    [encoder encodeBool:self.gotItem6 forKey:@"gotItem6"];
    [encoder encodeBool:self.gotItem7 forKey:@"gotItem7"];
    [encoder encodeBool:self.gotItem8 forKey:@"gotItem8"];
    [encoder encodeBool:self.gotItem9 forKey:@"gotItem9"];
    [encoder encodeBool:self.gotItem10 forKey:@"gotItem10"];
    [encoder encodeBool:self.gotItem11 forKey:@"gotItem11"];
    [encoder encodeBool:self.gotItem12 forKey:@"gotItem12"];
    [encoder encodeBool:self.gotItem13 forKey:@"gotItem13"];
    [encoder encodeBool:self.gotItem14 forKey:@"gotItem14"];
    [encoder encodeBool:self.gotItem15 forKey:@"gotItem15"];
    [encoder encodeBool:self.gotItem16 forKey:@"gotItem16"];
    [encoder encodeBool:self.gotItem17 forKey:@"gotItem17"];
    [encoder encodeBool:self.gotItem18 forKey:@"gotItem18"];
    [encoder encodeBool:self.gotItem19 forKey:@"gotItem19"];
    [encoder encodeBool:self.gotItem20 forKey:@"gotItem20"];
    [encoder encodeBool:self.gotItem21 forKey:@"gotItem21"];
    [encoder encodeBool:self.gotItem22 forKey:@"gotItem22"];
    [encoder encodeBool:self.gotItem23 forKey:@"gotItem23"];
    [encoder encodeBool:self.gotItem24 forKey:@"gotItem24"];
    [encoder encodeBool:self.gotItem25 forKey:@"gotItem25"];
    [encoder encodeBool:self.gotItem26 forKey:@"gotItem26"];
    [encoder encodeBool:self.gotItem27 forKey:@"gotItem27"];
    [encoder encodeBool:self.gotItem28 forKey:@"gotItem28"];
    [encoder encodeBool:self.gotItem29 forKey:@"gotItem29"];
    [encoder encodeBool:self.gotItem30 forKey:@"gotItem30"];
    [encoder encodeBool:self.gotItem31 forKey:@"gotItem31"];
    [encoder encodeBool:self.gotItem32 forKey:@"gotItem32"];
    [encoder encodeBool:self.gotItem33 forKey:@"gotItem33"];
    [encoder encodeBool:self.gotItem34 forKey:@"gotItem34"];
    [encoder encodeBool:self.gotItem35 forKey:@"gotItem35"];
    [encoder encodeBool:self.gotItem36 forKey:@"gotItem36"];
    [encoder encodeBool:self.gotItem37 forKey:@"gotItem37"];
    [encoder encodeBool:self.gotItem38 forKey:@"gotItem38"];
    [encoder encodeBool:self.gotItem39 forKey:@"gotItem39"];
    [encoder encodeBool:self.gotItem40 forKey:@"gotItem40"];
    [encoder encodeBool:self.gotItem41 forKey:@"gotItem41"];
    [encoder encodeBool:self.gotItem42 forKey:@"gotItem42"];
    [encoder encodeBool:self.gotItem43 forKey:@"gotItem43"];
    [encoder encodeBool:self.gotItem44 forKey:@"gotItem44"];
    [encoder encodeBool:self.gotItem45 forKey:@"gotItem45"];
    [encoder encodeBool:self.gotItem46 forKey:@"gotItem46"];
    [encoder encodeBool:self.gotItem47 forKey:@"gotItem47"];
    [encoder encodeBool:self.gotItem48 forKey:@"gotItem48"];
    [encoder encodeBool:self.gotItem49 forKey:@"gotItem49"];
    [encoder encodeBool:self.gotItem50 forKey:@"gotItem50"];
    [encoder encodeBool:self.gotItem51 forKey:@"gotItem51"];
    [encoder encodeBool:self.gotItem52 forKey:@"gotItem52"];
    [encoder encodeBool:self.gotItem53 forKey:@"gotItem53"];
    [encoder encodeBool:self.gotItem54 forKey:@"gotItem54"];
    [encoder encodeBool:self.gotItem55 forKey:@"gotItem55"];
    [encoder encodeBool:self.gotItem56 forKey:@"gotItem56"];
    [encoder encodeBool:self.gotItem57 forKey:@"gotItem57"];
    [encoder encodeBool:self.gotItem58 forKey:@"gotItem58"];
    [encoder encodeBool:self.gotItem59 forKey:@"gotItem59"];
    [encoder encodeBool:self.gotItem60 forKey:@"gotItem60"];
    [encoder encodeBool:self.gotItem61 forKey:@"gotItem61"];
    [encoder encodeBool:self.gotItem62 forKey:@"gotItem62"];
    [encoder encodeBool:self.gotItem63 forKey:@"gotItem63"];
    
    [encoder encodeBool:self.gotLorica forKey:@"gotLorica"];
    [encoder encodeBool:self.introducedToKingV forKey:@"introducedToKingV"];
    [encoder encodeBool:self.gotOrb forKey:@"gotOrb"];
    [encoder encodeBool:self.killedBugs forKey:@"killedBugs"];
    [encoder encodeBool:self.beatIonak forKey:@"beatIonak"];
    [encoder encodeBool:self.acceptedMessageKingK forKey:@"acceptedMessageKingK"];
    [encoder encodeBool:self.acceptedTaskTraveler forKey:@"acceptedTaskTraveler"];
    [encoder encodeBool:self.acceptedFindEilifKingV forKey:@"acceptedFindEilifKingV"];
    [encoder encodeBool:self.acceptedTaskKingVPostOrb forKey:@"acceptedTaskKingVPostOrb"];
    [encoder encodeBool:self.deliveredLetterToKingK forKey:@"deliveredLetterToKingK"];
    [encoder encodeBool:self.hasLitOrb forKey:@"hasLitOrb"];
    [encoder encodeBool:self.toldNewsKingV forKey:@"toldNewsKingV"];
    [encoder encodeBool:self.talkedToKingVInitial forKey:@"talkedToKingVInitial"];
    [encoder encodeBool:self.talkedToKingVPostOrb forKey:@"talkedToKingVPostOrb"];
    [encoder encodeBool:self.finishedTaskTraveler forKey:@"finishedTaskTraveler"];
    [encoder encodeBool:self.beatDragon forKey:@"beatDragon"];
    [encoder encodeBool:self.beatCyclops forKey:@"beatCyclops"];
    [encoder encodeBool:self.beatCaveBoss forKey:@"beatCaveBoss"];
    [encoder encodeBool:self.talkedToArnuk forKey:@"talkedToArnuk"];
    [encoder encodeBool:self.talkedToEilif forKey:@"talkedToEilif"];
    [encoder encodeBool:self.savedKing forKey:@"savedKing"];
    [encoder encodeBool:self.gotPrizeFromKingV forKey:@"gotPrizeFromKingV"];
    [encoder encodeBool:self.gotRepellent forKey:@"gotRepellent"];

    [encoder encodeDouble:self.sprite1position.x forKey:@"sprite1position.x"];
    [encoder encodeDouble:self.sprite1position.y forKey:@"sprite1position.y"];

    [encoder encodeInt:self.heroAtkStyle forKey:@"heroAtkStyle"];
    [encoder encodeBool:self.gotFireRoot forKey:@"gotFireRoot"];
    [encoder encodeBool:self.talkedToEilifPostBoss forKey:@"talkedToEilifPostBoss"];
    [encoder encodeBool:self.talkedToWatchmen forKey:@"talkedToWatchmen"];
    [encoder encodeBool:self.usedBook forKey:@"usedBook"];

    [encoder encodeDouble:self.attribGoldMult forKey:@"attribGoldMult"];
    [encoder encodeDouble:self.attribExpMult forKey:@"attribExpMult"];
    
    [encoder encodeInt:self.heroCurrentHP forKey:@"heroCurrentHP"];
    [encoder encodeInt:self.gold forKey:@"gold"];
    [encoder encodeInt:self.exp forKey:@"exp"];
    [encoder encodeInt:self.heroHP forKey:@"heroHP"];
    [encoder encodeInt:self.heroStr forKey:@"heroStr"];
    [encoder encodeInt:self.defBonus forKey:@"defBonus"];
    [encoder encodeObject:self.heroName forKey:@"heroName"];
    
    [encoder encodeInt:self.position.x forKey:@"position.x"];
    [encoder encodeInt:self.position.y forKey:@"position.y"];
    
    [encoder encodeInt:self.strBonus forKey:@"strBonus"];
    [encoder encodeInt:self.currentMap forKey:@"currentMap"];
    [encoder encodeInt:self.freePoints forKey:@"freePoints"];
    [encoder encodeInt:self.heroStrDef forKey:@"heroStrDef"];
    
    [encoder encodeObject:[NSKeyedArchiver archivedDataWithRootObject:self.heroInventory] forKey:@"heroInventory"];
    
    [encoder encodeInt:self.heroOrientation forKey:@"heroOrientation"];
    [encoder encodeInt:self.heroLvl forKey:@"heroLvl"];
    [encoder encodeInt:self.heroSPD forKey:@"heroSPD"];
    [encoder encodeInt:self.attributePoints forKey:@"attributePoints"];
    [encoder encodeInt:self.aglBonus forKey:@"aglBonus"];
    
    [encoder encodeDouble:self.defMult forKey:@"defMult"];
    [encoder encodeDouble:self.strMult forKey:@"strMult"];
    [encoder encodeDouble:self.aglMult forKey:@"aglMult"];
    
    [encoder encodeObject:self.equipPos1 forKey:@"equipPos1"];
    [encoder encodeObject:self.equipPos2 forKey:@"equipPos2"];
    [encoder encodeObject:self.equipPos3 forKey:@"equipPos3"];
    [encoder encodeObject:self.equipPos4 forKey:@"equipPos4"];
    [encoder encodeObject:self.equipPos5 forKey:@"equipPos5"];
    [encoder encodeObject:self.equipPos6 forKey:@"equipPos6"];
    
    [encoder encodeBool:self.attrib1 forKey:@"attrib1"];
    [encoder encodeBool:self.attrib2 forKey:@"attrib2"];
    [encoder encodeBool:self.attrib3 forKey:@"attrib3"];
    [encoder encodeBool:self.attrib4 forKey:@"attrib4"];
    [encoder encodeBool:self.attrib5 forKey:@"attrib5"];
    [encoder encodeBool:self.attrib6 forKey:@"attrib6"];
    [encoder encodeBool:self.attrib7 forKey:@"attrib7"];
    [encoder encodeBool:self.attrib8 forKey:@"attrib8"];
    [encoder encodeBool:self.attrib9 forKey:@"attrib9"];
    [encoder encodeBool:self.attrib10 forKey:@"attrib10"];
    [encoder encodeBool:self.attrib11 forKey:@"attrib11"];
    [encoder encodeBool:self.attrib12 forKey:@"attrib12"];
    [encoder encodeBool:self.attrib13 forKey:@"attrib13"];
    [encoder encodeBool:self.attrib14 forKey:@"attrib14"];
    [encoder encodeBool:self.attrib15 forKey:@"attrib15"];
    [encoder encodeBool:self.attrib16 forKey:@"attrib16"];
    [encoder encodeBool:self.attrib17 forKey:@"attrib17"];
    [encoder encodeBool:self.attrib18 forKey:@"attrib18"];
    [encoder encodeBool:self.attrib19 forKey:@"attrib19"];
    
    [encoder encodeDouble:self.attribAgiMult forKey:@"attribAgiMult"];
    [encoder encodeDouble:self.attribDefMult forKey:@"attribDefMult"];
    [encoder encodeDouble:self.attribStrMult forKey:@"attribStrMult"];
    
    [encoder encodeBool:self.itemInPos1 forKey:@"itemInPos1"];
    [encoder encodeBool:self.itemInPos2 forKey:@"itemInPos2"];
    [encoder encodeBool:self.itemInPos3 forKey:@"itemInPos3"];
    [encoder encodeBool:self.itemInPos4 forKey:@"itemInPos4"];
    [encoder encodeBool:self.itemInPos5 forKey:@"itemInPos5"];
    [encoder encodeBool:self.itemInPos6 forKey:@"itemInPos6"];
    
    [encoder encodeDouble:self.itemExpMult forKey:@"itemExpMult"];
    [encoder encodeDouble:self.itemGoldMult forKey:@"itemGoldMult"];
    
    [encoder encodeInt:self.mapInitMode forKey:@"mapInitMode"];
    [encoder encodeInt:self.musicCode forKey:@"musicCode"];
    
    
    [encoder encodeDouble:self.sprite2position.x forKey:@"sprite2position.x"];
    [encoder encodeDouble:self.sprite2position.y forKey:@"sprite2position.y"];
    [encoder encodeDouble:self.sprite3position.x forKey:@"sprite3position.x"];
    [encoder encodeDouble:self.sprite3position.y forKey:@"sprite3position.y"];
    [encoder encodeDouble:self.sprite4position.x forKey:@"sprite4position.x"];
    [encoder encodeDouble:self.sprite4position.y forKey:@"sprite4position.y"];
    [encoder encodeDouble:self.sprite5position.x forKey:@"sprite5position.x"];
    [encoder encodeDouble:self.sprite5position.y forKey:@"sprite5position.y"];
    [encoder encodeDouble:self.sprite6position.x forKey:@"sprite6position.x"];
    [encoder encodeDouble:self.sprite6position.y forKey:@"sprite6position.y"];
    [encoder encodeDouble:self.sprite7position.x forKey:@"sprite7position.x"];
    [encoder encodeDouble:self.sprite7position.y forKey:@"sprite7position.y"];
    [encoder encodeDouble:self.sprite8position.x forKey:@"sprite8position.x"];
    [encoder encodeDouble:self.sprite8position.y forKey:@"sprite8position.y"];
    [encoder encodeDouble:self.sprite9position.x forKey:@"sprite9position.x"];
    [encoder encodeDouble:self.sprite9position.y forKey:@"sprite9position.y"];
    [encoder encodeDouble:self.sprite10position.x forKey:@"sprite10position.x"];
    [encoder encodeDouble:self.sprite10position.y forKey:@"sprite10position.y"];
    [encoder encodeDouble:self.sprite11position.x forKey:@"sprite11position.x"];
    [encoder encodeDouble:self.sprite11position.y forKey:@"sprite11position.y"];
    [encoder encodeDouble:self.sprite12position.x forKey:@"sprite12position.x"];
    [encoder encodeDouble:self.sprite12position.y forKey:@"sprite12position.y"];
    [encoder encodeDouble:self.sprite13position.x forKey:@"sprite13position.x"];
    [encoder encodeDouble:self.sprite13position.y forKey:@"sprite13position.y"];
    [encoder encodeDouble:self.sprite14position.x forKey:@"sprite14position.x"];
    [encoder encodeDouble:self.sprite14position.y forKey:@"sprite14position.y"];
    [encoder encodeDouble:self.sprite15position.x forKey:@"sprite15position.x"];
    [encoder encodeDouble:self.sprite15position.y forKey:@"sprite15position.y"];
    [encoder encodeDouble:self.sprite16position.x forKey:@"sprite16position.x"];
    [encoder encodeDouble:self.sprite16position.y forKey:@"sprite16position.y"];
    [encoder encodeDouble:self.sprite17position.x forKey:@"sprite17position.x"];
    [encoder encodeDouble:self.sprite17position.y forKey:@"sprite17position.y"];
    [encoder encodeDouble:self.sprite18position.x forKey:@"sprite18position.x"];
    [encoder encodeDouble:self.sprite18position.y forKey:@"sprite18position.y"];
    [encoder encodeDouble:self.sprite19position.x forKey:@"sprite19position.x"];
    [encoder encodeDouble:self.sprite19position.y forKey:@"sprite19position.y"];
    [encoder encodeDouble:self.sprite20position.x forKey:@"sprite20position.x"];
    [encoder encodeDouble:self.sprite20position.y forKey:@"sprite20position.y"];
    [encoder encodeDouble:self.sprite21position.x forKey:@"sprite21position.x"];
    [encoder encodeDouble:self.sprite21position.y forKey:@"sprite21position.y"];
    [encoder encodeDouble:self.sprite22position.x forKey:@"sprite22position.x"];
    [encoder encodeDouble:self.sprite22position.y forKey:@"sprite22position.y"];
    [encoder encodeDouble:self.sprite23position.x forKey:@"sprite23position.x"];
    [encoder encodeDouble:self.sprite23position.y forKey:@"sprite23position.y"];
    [encoder encodeDouble:self.sprite24position.x forKey:@"sprite24position.x"];
    [encoder encodeDouble:self.sprite24position.y forKey:@"sprite24position.y"];
    [encoder encodeDouble:self.sprite25position.x forKey:@"sprite25position.x"];
    [encoder encodeDouble:self.sprite25position.y forKey:@"sprite25position.y"];
    [encoder encodeDouble:self.sprite26position.x forKey:@"sprite26position.x"];
    [encoder encodeDouble:self.sprite26position.y forKey:@"sprite26position.y"];
    [encoder encodeDouble:self.sprite27position.x forKey:@"sprite27position.x"];
    [encoder encodeDouble:self.sprite27position.y forKey:@"sprite27position.y"];
    
    [encoder encodeInt:self.sprite1_Orientation forKey:@"sprite1_Orientation"];
    [encoder encodeInt:self.sprite2_Orientation forKey:@"sprite2_Orientation"];
    [encoder encodeInt:self.sprite3_Orientation forKey:@"sprite3_Orientation"];
    [encoder encodeInt:self.sprite4_Orientation forKey:@"sprite4_Orientation"];
    [encoder encodeInt:self.sprite5_Orientation forKey:@"sprite5_Orientation"];
    [encoder encodeInt:self.sprite6_Orientation forKey:@"sprite6_Orientation"];
    [encoder encodeInt:self.sprite7_Orientation forKey:@"sprite7_Orientation"];
    [encoder encodeInt:self.sprite8_Orientation forKey:@"sprite8_Orientation"];
    [encoder encodeInt:self.sprite9_Orientation forKey:@"sprite9_Orientation"];
    [encoder encodeInt:self.sprite10_Orientation forKey:@"sprite10_Orientation"];
    [encoder encodeInt:self.sprite11_Orientation forKey:@"sprite11_Orientation"];
    [encoder encodeInt:self.sprite12_Orientation forKey:@"sprite12_Orientation"];
    [encoder encodeInt:self.sprite13_Orientation forKey:@"sprite13_Orientation"];
    [encoder encodeInt:self.sprite14_Orientation forKey:@"sprite14_Orientation"];
    [encoder encodeInt:self.sprite15_Orientation forKey:@"sprite15_Orientation"];
    [encoder encodeInt:self.sprite16_Orientation forKey:@"sprite16_Orientation"];
    [encoder encodeInt:self.sprite17_Orientation forKey:@"sprite17_Orientation"];
    [encoder encodeInt:self.sprite18_Orientation forKey:@"sprite18_Orientation"];
    [encoder encodeInt:self.sprite19_Orientation forKey:@"sprite19_Orientation"];
    [encoder encodeInt:self.sprite20_Orientation forKey:@"sprite20_Orientation"];
    [encoder encodeInt:self.sprite21_Orientation forKey:@"sprite21_Orientation"];
    [encoder encodeInt:self.sprite22_Orientation forKey:@"sprite22_Orientation"];
    [encoder encodeInt:self.sprite23_Orientation forKey:@"sprite23_Orientation"];
    [encoder encodeInt:self.sprite24_Orientation forKey:@"sprite24_Orientation"];
    [encoder encodeInt:self.sprite25_Orientation forKey:@"sprite25_Orientation"];
    [encoder encodeInt:self.sprite26_Orientation forKey:@"sprite26_Orientation"];
    [encoder encodeInt:self.sprite27_Orientation forKey:@"sprite27_Orientation"];
    
    [encoder encodeInt:self.sprite30_Orientation forKey:@"sprite30_Orientation"];
    [encoder encodeInt:self.sprite31_Orientation forKey:@"sprite31_Orientation"];
    [encoder encodeInt:self.sprite32_Orientation forKey:@"sprite32_Orientation"];
    [encoder encodeInt:self.sprite33_Orientation forKey:@"sprite33_Orientation"];
    [encoder encodeInt:self.sprite34_Orientation forKey:@"sprite34_Orientation"];
    [encoder encodeInt:self.sprite35_Orientation forKey:@"sprite35_Orientation"];
    [encoder encodeInt:self.sprite36_Orientation forKey:@"sprite36_Orientation"];
    [encoder encodeInt:self.sprite37_Orientation forKey:@"sprite37_Orientation"];
    [encoder encodeInt:self.sprite38_Orientation forKey:@"sprite38_Orientation"];
    [encoder encodeInt:self.sprite39_Orientation forKey:@"sprite39_Orientation"];
    [encoder encodeInt:self.sprite40_Orientation forKey:@"sprite40_Orientation"];
    [encoder encodeInt:self.sprite41_Orientation forKey:@"sprite41_Orientation"];
    [encoder encodeInt:self.sprite42_Orientation forKey:@"sprite42_Orientation"];
    [encoder encodeInt:self.sprite43_Orientation forKey:@"sprite43_Orientation"];
    [encoder encodeInt:self.sprite44_Orientation forKey:@"sprite44_Orientation"];
    [encoder encodeInt:self.sprite45_Orientation forKey:@"sprite45_Orientation"];
    [encoder encodeInt:self.sprite46_Orientation forKey:@"sprite46_Orientation"];
    [encoder encodeInt:self.sprite47_Orientation forKey:@"sprite47_Orientation"];
    [encoder encodeInt:self.sprite48_Orientation forKey:@"sprite48_Orientation"];
    [encoder encodeInt:self.sprite49_Orientation forKey:@"sprite49_Orientation"];
    [encoder encodeInt:self.sprite50_Orientation forKey:@"sprite50_Orientation"];
    [encoder encodeInt:self.sprite51_Orientation forKey:@"sprite51_Orientation"];
    [encoder encodeInt:self.sprite52_Orientation forKey:@"sprite52_Orientation"];
    [encoder encodeInt:self.sprite53_Orientation forKey:@"sprite53_Orientation"];
    
    [encoder encodeDouble:self.sprite30position.x forKey:@"sprite30position.x"];
    [encoder encodeDouble:self.sprite30position.y forKey:@"sprite30position.y"];
    [encoder encodeDouble:self.sprite31position.x forKey:@"sprite31position.x"];
    [encoder encodeDouble:self.sprite31position.y forKey:@"sprite31position.y"];
    [encoder encodeDouble:self.sprite32position.x forKey:@"sprite32position.x"];
    [encoder encodeDouble:self.sprite32position.y forKey:@"sprite32position.y"];
    [encoder encodeDouble:self.sprite33position.x forKey:@"sprite33position.x"];
    [encoder encodeDouble:self.sprite33position.y forKey:@"sprite33position.y"];
    [encoder encodeDouble:self.sprite34position.x forKey:@"sprite34position.x"];
    [encoder encodeDouble:self.sprite34position.y forKey:@"sprite34position.y"];
    [encoder encodeDouble:self.sprite35position.x forKey:@"sprite35position.x"];
    [encoder encodeDouble:self.sprite35position.y forKey:@"sprite35position.y"];
    [encoder encodeDouble:self.sprite36position.x forKey:@"sprite36position.x"];
    [encoder encodeDouble:self.sprite36position.y forKey:@"sprite36position.y"];
    [encoder encodeDouble:self.sprite37position.x forKey:@"sprite37position.x"];
    [encoder encodeDouble:self.sprite37position.y forKey:@"sprite37position.y"];
    [encoder encodeDouble:self.sprite38position.x forKey:@"sprite38position.x"];
    [encoder encodeDouble:self.sprite38position.y forKey:@"sprite38position.y"];
    [encoder encodeDouble:self.sprite39position.x forKey:@"sprite39position.x"];
    [encoder encodeDouble:self.sprite39position.y forKey:@"sprite39position.y"];
    [encoder encodeDouble:self.sprite40position.x forKey:@"sprite40position.x"];
    [encoder encodeDouble:self.sprite40position.y forKey:@"sprite40position.y"];
    [encoder encodeDouble:self.sprite41position.x forKey:@"sprite41position.x"];
    [encoder encodeDouble:self.sprite41position.y forKey:@"sprite41position.y"];
    [encoder encodeDouble:self.sprite42position.x forKey:@"sprite42position.x"];
    [encoder encodeDouble:self.sprite42position.y forKey:@"sprite42position.y"];
    [encoder encodeDouble:self.sprite43position.x forKey:@"sprite43position.x"];
    [encoder encodeDouble:self.sprite43position.y forKey:@"sprite43position.y"];
    [encoder encodeDouble:self.sprite44position.x forKey:@"sprite44position.x"];
    [encoder encodeDouble:self.sprite44position.y forKey:@"sprite44position.y"];
    [encoder encodeDouble:self.sprite45position.x forKey:@"sprite45position.x"];
    [encoder encodeDouble:self.sprite45position.y forKey:@"sprite45position.y"];
    [encoder encodeDouble:self.sprite46position.x forKey:@"sprite46position.x"];
    [encoder encodeDouble:self.sprite46position.y forKey:@"sprite46position.y"];
    [encoder encodeDouble:self.sprite47position.x forKey:@"sprite47position.x"];
    [encoder encodeDouble:self.sprite47position.y forKey:@"sprite47position.y"];
    [encoder encodeDouble:self.sprite48position.x forKey:@"sprite48position.x"];
    [encoder encodeDouble:self.sprite48position.y forKey:@"sprite48position.y"];
    [encoder encodeDouble:self.sprite49position.x forKey:@"sprite49position.x"];
    [encoder encodeDouble:self.sprite49position.y forKey:@"sprite49position.y"];
    [encoder encodeDouble:self.sprite50position.x forKey:@"sprite50position.x"];
    [encoder encodeDouble:self.sprite50position.y forKey:@"sprite50position.y"];
    [encoder encodeDouble:self.sprite51position.x forKey:@"sprite51position.x"];
    [encoder encodeDouble:self.sprite51position.y forKey:@"sprite51position.y"];
    [encoder encodeDouble:self.sprite52position.x forKey:@"sprite52position.x"];
    [encoder encodeDouble:self.sprite52position.y forKey:@"sprite52position.y"];
    [encoder encodeDouble:self.sprite53position.x forKey:@"sprite53position.x"];
    [encoder encodeDouble:self.sprite53position.y forKey:@"sprite53position.y"];
    
    [encoder encodeInt:self.sprite61_Orientation forKey:@"sprite61_Orientation"];
    [encoder encodeInt:self.sprite62_Orientation forKey:@"sprite62_Orientation"];
    [encoder encodeInt:self.sprite63_Orientation forKey:@"sprite63_Orientation"];
    [encoder encodeInt:self.sprite64_Orientation forKey:@"sprite64_Orientation"];
    [encoder encodeInt:self.sprite65_Orientation forKey:@"sprite65_Orientation"];
    [encoder encodeInt:self.sprite66_Orientation forKey:@"sprite66_Orientation"];
    [encoder encodeInt:self.sprite67_Orientation forKey:@"sprite67_Orientation"];
    [encoder encodeInt:self.sprite68_Orientation forKey:@"sprite68_Orientation"];
    [encoder encodeInt:self.sprite69_Orientation forKey:@"sprite69_Orientation"];
    [encoder encodeInt:self.sprite70_Orientation forKey:@"sprite70_Orientation"];
    [encoder encodeInt:self.sprite71_Orientation forKey:@"sprite71_Orientation"];
    [encoder encodeInt:self.sprite72_Orientation forKey:@"sprite72_Orientation"];
    [encoder encodeInt:self.sprite73_Orientation forKey:@"sprite73_Orientation"];
    [encoder encodeInt:self.sprite74_Orientation forKey:@"sprite74_Orientation"];
    [encoder encodeInt:self.sprite75_Orientation forKey:@"sprite75_Orientation"];
    [encoder encodeInt:self.sprite76_Orientation forKey:@"sprite76_Orientation"];
    
    [encoder encodeDouble:self.sprite61position.x forKey:@"sprite61position.x"];
    [encoder encodeDouble:self.sprite61position.y forKey:@"sprite61position.y"];
    [encoder encodeDouble:self.sprite62position.x forKey:@"sprite62position.x"];
    [encoder encodeDouble:self.sprite62position.y forKey:@"sprite62position.y"];
    [encoder encodeDouble:self.sprite63position.x forKey:@"sprite63position.x"];
    [encoder encodeDouble:self.sprite63position.y forKey:@"sprite63position.y"];
    [encoder encodeDouble:self.sprite64position.x forKey:@"sprite64position.x"];
    [encoder encodeDouble:self.sprite64position.y forKey:@"sprite64position.y"];
    [encoder encodeDouble:self.sprite65position.x forKey:@"sprite65position.x"];
    [encoder encodeDouble:self.sprite65position.y forKey:@"sprite65position.y"];
    [encoder encodeDouble:self.sprite66position.x forKey:@"sprite66position.x"];
    [encoder encodeDouble:self.sprite66position.y forKey:@"sprite66position.y"];
    [encoder encodeDouble:self.sprite67position.x forKey:@"sprite67position.x"];
    [encoder encodeDouble:self.sprite67position.y forKey:@"sprite67position.y"];
    [encoder encodeDouble:self.sprite68position.x forKey:@"sprite68position.x"];
    [encoder encodeDouble:self.sprite68position.y forKey:@"sprite68position.y"];
    [encoder encodeDouble:self.sprite69position.x forKey:@"sprite69position.x"];
    [encoder encodeDouble:self.sprite69position.y forKey:@"sprite69position.y"];
    [encoder encodeDouble:self.sprite70position.x forKey:@"sprite70position.x"];
    [encoder encodeDouble:self.sprite70position.y forKey:@"sprite70position.y"];
    [encoder encodeDouble:self.sprite71position.x forKey:@"sprite71position.x"];
    [encoder encodeDouble:self.sprite71position.y forKey:@"sprite71position.y"];
    [encoder encodeDouble:self.sprite72position.x forKey:@"sprite72position.x"];
    [encoder encodeDouble:self.sprite72position.y forKey:@"sprite72position.y"];
    [encoder encodeDouble:self.sprite73position.x forKey:@"sprite73position.x"];
    [encoder encodeDouble:self.sprite73position.y forKey:@"sprite73position.y"];
    [encoder encodeDouble:self.sprite74position.x forKey:@"sprite74position.x"];
    [encoder encodeDouble:self.sprite74position.y forKey:@"sprite74position.y"];
    [encoder encodeDouble:self.sprite75position.x forKey:@"sprite75position.x"];
    [encoder encodeDouble:self.sprite75position.y forKey:@"sprite75position.y"];
    [encoder encodeDouble:self.sprite76position.x forKey:@"sprite76position.x"];
    [encoder encodeDouble:self.sprite76position.y forKey:@"sprite76position.y"];
    
    [encoder encodeBool:self.beatVank forKey:@"beatVank"];
    [encoder encodeBool:self.beatTitan forKey:@"beatTitan"];
    [encoder encodeBool:self.beatCaveTroll forKey:@"beatCaveTroll"];
    [encoder encodeBool:self.beatIceGolem1 forKey:@"beatIceGolem1"];
    [encoder encodeBool:self.beatIceGolem2 forKey:@"beatIceGolem2"];
    [encoder encodeBool:self.beatIceGolem3 forKey:@"beatIceGolem3"];
    [encoder encodeBool:self.beatSunDragon forKey:@"beatSunDragon"];
    [encoder encodeBool:self.beatTowerKeeper forKey:@"beatTowerKeeper"];
    [encoder encodeBool:self.gotEarthSword forKey:@"gotEarthSword"];
    [encoder encodeBool:self.beatTraveler forKey:@"beatTraveler"];
    
    [encoder encodeInt:self.sprite81_Orientation forKey:@"sprite81_Orientation"];
    [encoder encodeInt:self.sprite82_Orientation forKey:@"sprite82_Orientation"];
    [encoder encodeInt:self.sprite83_Orientation forKey:@"sprite83_Orientation"];
    [encoder encodeInt:self.sprite84_Orientation forKey:@"sprite84_Orientation"];
    [encoder encodeInt:self.sprite85_Orientation forKey:@"sprite85_Orientation"];
    [encoder encodeInt:self.sprite86_Orientation forKey:@"sprite86_Orientation"];
    [encoder encodeInt:self.sprite87_Orientation forKey:@"sprite87_Orientation"];
    [encoder encodeInt:self.sprite88_Orientation forKey:@"sprite88_Orientation"];
    [encoder encodeInt:self.sprite89_Orientation forKey:@"sprite89_Orientation"];
    [encoder encodeInt:self.sprite90_Orientation forKey:@"sprite90_Orientation"];
    [encoder encodeInt:self.sprite91_Orientation forKey:@"sprite91_Orientation"];
    [encoder encodeInt:self.sprite92_Orientation forKey:@"sprite92_Orientation"];
    [encoder encodeInt:self.sprite93_Orientation forKey:@"sprite93_Orientation"];
    [encoder encodeInt:self.sprite94_Orientation forKey:@"sprite94_Orientation"];
    [encoder encodeInt:self.sprite95_Orientation forKey:@"sprite95_Orientation"];
    [encoder encodeInt:self.sprite96_Orientation forKey:@"sprite96_Orientation"];
    [encoder encodeInt:self.sprite97_Orientation forKey:@"sprite97_Orientation"];
    [encoder encodeInt:self.sprite98_Orientation forKey:@"sprite98_Orientation"];
    [encoder encodeInt:self.sprite99_Orientation forKey:@"sprite99_Orientation"];
    [encoder encodeInt:self.sprite100_Orientation forKey:@"sprite100_Orientation"];
    [encoder encodeInt:self.sprite101_Orientation forKey:@"sprite101_Orientation"];
    [encoder encodeInt:self.sprite102_Orientation forKey:@"sprite102_Orientation"];
    [encoder encodeInt:self.sprite103_Orientation forKey:@"sprite103_Orientation"];
    [encoder encodeInt:self.sprite104_Orientation forKey:@"sprite104_Orientation"];
    
    [encoder encodeDouble:self.sprite81position.x forKey:@"sprite81position.x"];
    [encoder encodeDouble:self.sprite81position.y forKey:@"sprite81position.y"];
    [encoder encodeDouble:self.sprite82position.x forKey:@"sprite82position.x"];
    [encoder encodeDouble:self.sprite82position.y forKey:@"sprite82position.y"];
    [encoder encodeDouble:self.sprite83position.x forKey:@"sprite83position.x"];
    [encoder encodeDouble:self.sprite83position.y forKey:@"sprite83position.y"];
    [encoder encodeDouble:self.sprite84position.x forKey:@"sprite84position.x"];
    [encoder encodeDouble:self.sprite84position.y forKey:@"sprite84position.y"];
    [encoder encodeDouble:self.sprite85position.x forKey:@"sprite85position.x"];
    [encoder encodeDouble:self.sprite85position.y forKey:@"sprite85position.y"];
    [encoder encodeDouble:self.sprite86position.x forKey:@"sprite86position.x"];
    [encoder encodeDouble:self.sprite86position.y forKey:@"sprite86position.y"];
    [encoder encodeDouble:self.sprite87position.x forKey:@"sprite87position.x"];
    [encoder encodeDouble:self.sprite87position.y forKey:@"sprite87position.y"];
    [encoder encodeDouble:self.sprite88position.x forKey:@"sprite88position.x"];
    [encoder encodeDouble:self.sprite88position.y forKey:@"sprite88position.y"];
    [encoder encodeDouble:self.sprite89position.x forKey:@"sprite89position.x"];
    [encoder encodeDouble:self.sprite89position.y forKey:@"sprite89position.y"];
    [encoder encodeDouble:self.sprite90position.x forKey:@"sprite90position.x"];
    [encoder encodeDouble:self.sprite90position.y forKey:@"sprite90position.y"];
    [encoder encodeDouble:self.sprite91position.x forKey:@"sprite91position.x"];
    [encoder encodeDouble:self.sprite91position.y forKey:@"sprite91position.y"];
    [encoder encodeDouble:self.sprite92position.x forKey:@"sprite92position.x"];
    [encoder encodeDouble:self.sprite92position.y forKey:@"sprite92position.y"];
    [encoder encodeDouble:self.sprite93position.x forKey:@"sprite93position.x"];
    [encoder encodeDouble:self.sprite93position.y forKey:@"sprite93position.y"];
    [encoder encodeDouble:self.sprite94position.x forKey:@"sprite94position.x"];
    [encoder encodeDouble:self.sprite94position.y forKey:@"sprite94position.y"];
    [encoder encodeDouble:self.sprite95position.x forKey:@"sprite95position.x"];
    [encoder encodeDouble:self.sprite95position.y forKey:@"sprite95position.y"];
    [encoder encodeDouble:self.sprite96position.x forKey:@"sprite96position.x"];
    [encoder encodeDouble:self.sprite96position.y forKey:@"sprite96position.y"];
    [encoder encodeDouble:self.sprite97position.x forKey:@"sprite97position.x"];
    [encoder encodeDouble:self.sprite97position.y forKey:@"sprite97position.y"];
    [encoder encodeDouble:self.sprite98position.x forKey:@"sprite98position.x"];
    [encoder encodeDouble:self.sprite98position.y forKey:@"sprite98position.y"];
    [encoder encodeDouble:self.sprite99position.x forKey:@"sprite99position.x"];
    [encoder encodeDouble:self.sprite99position.y forKey:@"sprite99position.y"];
    [encoder encodeDouble:self.sprite100position.x forKey:@"sprite100position.x"];
    [encoder encodeDouble:self.sprite100position.y forKey:@"sprite100position.y"];
    [encoder encodeDouble:self.sprite101position.x forKey:@"sprite101position.x"];
    [encoder encodeDouble:self.sprite101position.y forKey:@"sprite101position.y"];
    [encoder encodeDouble:self.sprite102position.x forKey:@"sprite102position.x"];
    [encoder encodeDouble:self.sprite102position.y forKey:@"sprite102position.y"];
    [encoder encodeDouble:self.sprite103position.x forKey:@"sprite103position.x"];
    [encoder encodeDouble:self.sprite103position.y forKey:@"sprite103position.y"];
    [encoder encodeDouble:self.sprite104position.x forKey:@"sprite104position.x"];
    [encoder encodeDouble:self.sprite104position.y forKey:@"sprite104position.y"];
    
    [encoder encodeDouble:self.sprite111position.x forKey:@"sprite111position.x"];
    [encoder encodeDouble:self.sprite111position.y forKey:@"sprite111position.y"];
    [encoder encodeDouble:self.sprite112position.x forKey:@"sprite112position.x"];
    [encoder encodeDouble:self.sprite112position.y forKey:@"sprite112position.y"];
    [encoder encodeDouble:self.sprite113position.x forKey:@"sprite113position.x"];
    [encoder encodeDouble:self.sprite113position.y forKey:@"sprite113position.y"];
    [encoder encodeDouble:self.sprite114position.x forKey:@"sprite114position.x"];
    [encoder encodeDouble:self.sprite114position.y forKey:@"sprite114position.y"];
    [encoder encodeDouble:self.sprite115position.x forKey:@"sprite115position.x"];
    [encoder encodeDouble:self.sprite115position.y forKey:@"sprite115position.y"];
    [encoder encodeDouble:self.sprite116position.x forKey:@"sprite116position.x"];
    [encoder encodeDouble:self.sprite116position.y forKey:@"sprite116position.y"];
    [encoder encodeDouble:self.sprite117position.x forKey:@"sprite117position.x"];
    [encoder encodeDouble:self.sprite117position.y forKey:@"sprite117position.y"];
    [encoder encodeDouble:self.sprite118position.x forKey:@"sprite118position.x"];
    [encoder encodeDouble:self.sprite118position.y forKey:@"sprite118position.y"];
    [encoder encodeDouble:self.sprite119position.x forKey:@"sprite119position.x"];
    [encoder encodeDouble:self.sprite119position.y forKey:@"sprite119position.y"];
    [encoder encodeDouble:self.sprite120position.x forKey:@"sprite120position.x"];
    [encoder encodeDouble:self.sprite120position.y forKey:@"sprite120position.y"];
    [encoder encodeDouble:self.sprite121position.x forKey:@"sprite121position.x"];
    [encoder encodeDouble:self.sprite121position.y forKey:@"sprite121position.y"];
    [encoder encodeDouble:self.sprite122position.x forKey:@"sprite122position.x"];
    [encoder encodeDouble:self.sprite122position.y forKey:@"sprite122position.y"];
    [encoder encodeDouble:self.sprite123position.x forKey:@"sprite123position.x"];
    [encoder encodeDouble:self.sprite123position.y forKey:@"sprite123position.y"];
    [encoder encodeDouble:self.sprite124position.x forKey:@"sprite124position.x"];
    [encoder encodeDouble:self.sprite124position.y forKey:@"sprite124position.y"];
    [encoder encodeDouble:self.sprite125position.x forKey:@"sprite125position.x"];
    [encoder encodeDouble:self.sprite125position.y forKey:@"sprite125position.y"];
    [encoder encodeDouble:self.sprite126position.x forKey:@"sprite126position.x"];
    [encoder encodeDouble:self.sprite126position.y forKey:@"sprite126position.y"];
    [encoder encodeDouble:self.sprite127position.x forKey:@"sprite127position.x"];
    [encoder encodeDouble:self.sprite127position.y forKey:@"sprite127position.y"];
    [encoder encodeDouble:self.sprite128position.x forKey:@"sprite128position.x"];
    [encoder encodeDouble:self.sprite128position.y forKey:@"sprite128position.y"];
    [encoder encodeDouble:self.sprite129position.x forKey:@"sprite129position.x"];
    [encoder encodeDouble:self.sprite129position.y forKey:@"sprite129position.y"];
    [encoder encodeDouble:self.sprite130position.x forKey:@"sprite130position.x"];
    [encoder encodeDouble:self.sprite130position.y forKey:@"sprite130position.y"];
    
    [encoder encodeInt:self.sprite111_Orientation forKey:@"sprite111_Orientation"];
    [encoder encodeInt:self.sprite112_Orientation forKey:@"sprite112_Orientation"];
    [encoder encodeInt:self.sprite113_Orientation forKey:@"sprite113_Orientation"];
    [encoder encodeInt:self.sprite114_Orientation forKey:@"sprite114_Orientation"];
    [encoder encodeInt:self.sprite115_Orientation forKey:@"sprite115_Orientation"];
    [encoder encodeInt:self.sprite116_Orientation forKey:@"sprite116_Orientation"];
    [encoder encodeInt:self.sprite117_Orientation forKey:@"sprite117_Orientation"];
    [encoder encodeInt:self.sprite118_Orientation forKey:@"sprite118_Orientation"];
    [encoder encodeInt:self.sprite119_Orientation forKey:@"sprite119_Orientation"];
    [encoder encodeInt:self.sprite120_Orientation forKey:@"sprite120_Orientation"];
    [encoder encodeInt:self.sprite121_Orientation forKey:@"sprite121_Orientation"];
    [encoder encodeInt:self.sprite122_Orientation forKey:@"sprite122_Orientation"];
    [encoder encodeInt:self.sprite123_Orientation forKey:@"sprite123_Orientation"];
    [encoder encodeInt:self.sprite124_Orientation forKey:@"sprite124_Orientation"];
    [encoder encodeInt:self.sprite125_Orientation forKey:@"sprite125_Orientation"];
    [encoder encodeInt:self.sprite126_Orientation forKey:@"sprite126_Orientation"];
    [encoder encodeInt:self.sprite127_Orientation forKey:@"sprite127_Orientation"];
    [encoder encodeInt:self.sprite128_Orientation forKey:@"sprite128_Orientation"];
    [encoder encodeInt:self.sprite129_Orientation forKey:@"sprite129_Orientation"];
    [encoder encodeInt:self.sprite130_Orientation forKey:@"sprite130_Orientation"];

    [encoder encodeBool:self.isRainingPL1 forKey:@"isRainingPL1"];
    [encoder encodeBool:self.isRainingPL3 forKey:@"isRainingPL3"];
    [encoder encodeBool:self.isRainingPL4 forKey:@"isRainingPL4"];
    [encoder encodeBool:self.isSnowingPL6 forKey:@"isRainingPL6"];
    
}


@end




